### ISSUE TITLE
issue with vector icons

### ISSUE THREAD

**Issue by Frankenstein666** [Dimezis/BlurView#41] opened 2017-03-08 11:18 UTC
in layouts containing vector icons  beneath blurview, it also blurs the icons as well when phone is locked and unlocked, is there any workaround for this?

**Comment by Dimezis** [comment] 2017-03-08 11:54
Any screenshots, examples?
I don't understand what do you mean

**Comment by Frankenstein666** [comment] 2017-03-09 05:33
i have a navigation drawer using blurView, if i lock my phone with navigation drawer open vector icons underneath the navigation drawer also gets blurred as show in the image below.
![img_20170309_105623](https://cloud.githubusercontent.com/assets/11345511/23737221/a5dea05c-04b9-11e7-9ba4-c89daab9b204.jpg)

**Comment by Dimezis** [comment] 2017-03-09 08:23
I think it's a VectorDrawable issue related to caching mechanism.
I'll try to investigate and report it

**Comment by Dimezis** [comment] 2017-03-10 09:24
I spent some time investigating this issue and noticed that this bug is only reproducible on API levels where real `VectorDrawable` is used. Looks like `VectorDrawableCompat` doesn't have this issue.
I'm still trying to understand why is it happening but no luck so far.

**Comment by Dimezis** [comment] 2017-03-11 19:56
https://code.google.com/p/android/issues/detail?id=244910
Here's a reported bug.
I'd really appreciate any support

**Comment by Frankenstein666** [comment] 2017-03-14 07:43
i still get same issues with **VectorDrawableCompat** as i replace **android:src** attribute with **app:srcCompat**.

**Comment by Dimezis** [comment] 2017-03-14 08:32
Attribute namespace doesn't matter, starting from API 24 it's impossible to use VectorDrawableCompat, everything will be delegated to the real VectorDrawable.

If you want this to be fixed, we have to bring attention to the bug report

**Comment by etanhatch** [comment] 2017-03-14 16:34
I have the following solution, I can submit it as a pull request, in BlockingBlurController.java:

`
    @Override
    public void drawBlurredContent(Canvas canvas) {
        isMeDrawingNow = true;

        if (isBlurEnabled && internalCanvas != null) {
            internalCanvas.save();
            setupInternalCanvasMatrix();
            drawUnderlyingViews();
            internalCanvas.scale(1, 1); // MODIFIED FROM LIBRARY CODE - fixes icon scale issue
            internalCanvas.restore();

            blurAndSave();
            draw(canvas);
        }
    }`

**Comment by Dimezis** [comment] 2017-03-14 16:39
Good spot @etanhatch! Pretty clever workaround.
Regarding the PR, as you wish. If you want to be among the contributors, please do it. 
If not, I can do it today.

**Comment by Dimezis** [comment] 2017-03-14 23:19
@etanhatch I've just checked this workaround in RecyclerView, nothing has changed for me. Are you sure it's the only change you introduced?

**Comment by etanhatch** [comment] 2017-03-23 15:35
I don't see any other changes, but I realised that in some situations I've now still encountered the issue. More investigation seems to be needed on this.

**Comment by MahmoudAlyuDeen** [comment] 2017-07-19 22:53
I seriously like both this library and vector drawables.. I use vectors for menu items in an activity while the blur is in a bottom sheet that overlays that activity, any progress or work around?

**Comment by Dimezis** [comment] 2017-07-20 13:45
From bug-report thread: "The engineering team has fixed the issue that you have reported and it will be available in a future build."
Not sure in future build of what though

**Comment by trr-amsiq** [comment] 2017-10-06 17:29
@Dimezis thanks for this great library! 
Any idea if google has realized a fix yet?
I'm experiencing the same issue

**Comment by Dimezis** [comment] 2017-10-15 11:59
@trr-amsiq Well, I don't experience this on my Pixel (8.0.0) anymore. 
Kinda sad they fixed it on SDK level, not support lib level.

**Comment by TeTRA99** [comment] 2017-11-02 21:41
Hi there, same problem here... working ok on Android 8.0 but not in the rest.. :(

**Comment by TeTRA99** [comment] 2018-01-05 21:47
Couldn't go around this vector icon problem.. moving to other library..

**Comment by Dimezis** [comment] 2018-01-06 08:26
@tetra99 so let me get this straight, you know other library that doesn't have this issue, and instead of at least pointing out to it, you just complain here? You do realize I could have fixed it already if I knew some other approach?

**Comment by TeTRA99** [comment] 2018-01-10 19:00
@Dimezis let put this straight for you.. after implementing this library through all our app we realized of this problem, we tried to fix it and find a workaround, all in vain. The other library that we are using now is a pretty old one that is quite limited, so we use it only in a few screens, and without the effect we originally wanted. it's this one: https://github.com/allegro/fogger. I hope you can find something useful in it.

**Comment by adheus** [comment] 2018-06-08 16:51
This is happening with me too when using it as a background on Fragments, after I pop it from backstack, vector icons on the now current fragment are blurred. Any updates on this?

**Comment by Dimezis** [comment] 2018-06-08 17:31
Unfortunately no, this is a platform bug. It's fixed in Android 8+

**Comment by Dimezis** [comment] 2019-04-17 11:42
Fixed in 1.6.0

**Closed by Dimezis** 2019-04-17 11:42 UTC
