### ISSUE TITLE
Null pointer when updating from 1.5.0 to 1.6.0

### ISSUE THREAD

**Issue by TeTRA99** [Dimezis/BlurView#94] opened 2019-04-19 16:12 UTC
If I go back to 1.5.0, it works again.. any ideas what might be the problem?

java.lang.NullPointerException: Attempt to invoke virtual method 'void android.graphics.Bitmap.eraseColor(int)' on a null object reference
        at eightbitlab.com.blurview.BlockingBlurController.updateBlur(BlockingBlurController.java:138)
        at eightbitlab.com.blurview.BlockingBlurController$1.onPreDraw(BlockingBlurController.java:59)
        at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2265)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1286)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6536)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
        at android.view.Choreographer.doCallbacks(Choreographer.java:683)
        at android.view.Choreographer.doFrame(Choreographer.java:619)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6247)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:872)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:762)

**Comment by Dimezis** [comment] 2019-04-20 13:54
Please post your OS, phone, and when exactly this crash happens

**Comment by Dimezis** [comment] 2019-04-20 15:28
I believe it should be fixed in 1.6.1, but I couldn't reproduce it, so it's a bit of a guess

**Comment by TeTRA99** [comment] 2019-04-20 18:13
Hi Dimezis, thanks for the quick fix! I can confirm that it is indeed fixed in v1.6.1.

Just for the record -and to answer your previous question-, it happened when it was trying to set the content view: setContentView(R.layout.activity_main); where the first BlurView was present.
I tested it in a LG G5 running Android 7.0.

**Closed** 2019-04-20 18:13 UTC
