### ISSUE TITLE
Calling RS with no Context active

### ISSUE THREAD

**Issue by fuxuanyang11** [Dimezis/BlurView#150] opened 2021-08-01 10:50 UTC
This will happen if you use glide BlurTransformation library

**Comment by fuxuanyang11** [comment] 2021-08-01 10:56
On the same Activity， and recyclerview use glide BlurTransformation   a lot of imageview
https://github.com/wasabeef/glide-transformations

**Comment by Dimezis** [comment] 2021-08-01 10:57
It's a duplicate of https://github.com/Dimezis/BlurView/issues/146
Also, please provide more information

**Comment by fuxuanyang11** [comment] 2021-08-01 11:01
Is there a conflict between these two libraries?

**Comment by fuxuanyang11** [comment] 2021-08-01 11:02
If I remove BlurTransformation, I won’t have this problem

**Comment by fuxuanyang11** [comment] 2021-08-01 11:04
` public static Bitmap blur(Context context, Bitmap bitmap, int radius) throws RSRuntimeException {
    RenderScript rs = null;
    Allocation input = null;
    Allocation output = null;
    ScriptIntrinsicBlur blur = null;
    try {
      rs = RenderScript.create(context);
      rs.setMessageHandler(new RenderScript.RSMessageHandler());
      input = Allocation.createFromBitmap(rs, bitmap, Allocation.MipmapControl.MIPMAP_NONE,
        Allocation.USAGE_SCRIPT);
      output = Allocation.createTyped(rs, input.getType());
      blur = ScriptIntrinsicBlur.create(rs, Element.U8_4(rs));

      blur.setInput(input);
      blur.setRadius(radius);
      blur.forEach(output);
      output.copyTo(bitmap);
    } finally {
      if (rs != null) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
          RenderScript.releaseAllContexts();
        } else {
          rs.destroy();
        }
      }
      if (input != null) {
        input.destroy();
      }
      if (output != null) {
        output.destroy();
      }
      if (blur != null) {
        blur.destroy();
      }
    }

    return bitmap;
  }`
This is his blur method

**Comment by Dimezis** [comment] 2021-08-01 11:21
This is rather a bug in `glide-transformations` library.
The problem is here 
```Java
if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M) {
      RenderScript.releaseAllContexts();
}
```

They are destroying all RS contexts, even if they don't belong to them

**Comment by fuxuanyang11** [comment] 2021-08-01 11:42
I changed this to rs.destroy();, but it's still the same

**Comment by fuxuanyang11** [comment] 2021-08-01 11:58
Thank you, I found a solution

**Closed** 2021-08-01 12:10 UTC

**Comment by Dimezis** [comment] 2021-08-01 15:47
Would you mind sharing it? :)

**Comment by fuxuanyang11** [comment] 2021-08-02 01:43
He shows up again, if I have too many img use BlurTransformation

**Comment by fuxuanyang11** [comment] 2021-08-02 02:16
I just modify  
`RenderScript.releaseAllContexts()` to
`rs.destroy();`

**Comment by fuxuanyang11** [comment] 2021-08-02 02:16
![4MCM6CQB~ )AP0PGQVZQ}3X](https://user-images.githubusercontent.com/21265701/127795757-19685209-44fe-4a7e-9ffc-d02952301f52.png)

**Comment by zengcanxiang** [comment] 2022-06-02 12:06
@Dimezis 
hi
I see that the `RenderScript.releaseAllContexts` method comment does not affect the renderScript created by `RenderScript.createMultiContext` , Can this help us fix without tryCatch wrapping `Dimezis.BlurView.RenderScriptBlur.blur` method
